/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "Analytics": {
      "assignPublicIp": boolean
      "cluster": string
      "containers": any
      "securityGroups": any
      "subnets": any
      "taskDefinition": string
      "type": "sst.aws.Task"
    }
    "CookieSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DbBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "UpdateDb": {
      "assignPublicIp": boolean
      "cluster": string
      "containers": any
      "securityGroups": any
      "subnets": any
      "taskDefinition": string
      "type": "sst.aws.Task"
    }
    "Vpc": {
      "type": "sst.aws.Vpc"
    }
    "Web": {
      "service": string
      "type": "sst.aws.Service"
      "url": string
    }
  }
}

import "sst"
export {}