// /app/lib/seo/metas/person.ts
//
// Meta builders for /people — the catalog, the profile overview, and every
// /people/:id/<dimension> sub-route. Overview copy is bespoke (it leads with the
// facts people google: age, canton, occupation, contact); the sub-routes and the
// catalog are generated by the shared factories.

import type { MetaDescriptor } from "react-router";
import {
    type MetaLang,
    type EntityMetaCtx,
    SITE_NAME,
    metaLang,
    buildMeta,
    joinParts,
} from "./core";
import {
    type IndexMetaCtx,
    type EntityFacts,
    makeDimensionMeta,
    makeIndexMeta,
} from "./factory";
import { type MetaLoc, metaLoc, substitute, mt } from "./loc";
import { jsonLdTag } from "~/lib/seo/jsonld/graph";
import { breadcrumbListJsonLd } from "~/lib/seo/jsonld/breadcrumbs";
import { personNode } from "~/lib/seo/jsonld/person";
import { itemListJsonLd } from "~/lib/seo/jsonld/list";
import { makeDatasets } from "~/lib/seo/jsonld/dataset";
import { personNodeId } from "~/lib/seo/jsonld/ids";
import { URL_PATH_SEGMENTS } from "~/configs/site.config";
import type { ExportFeedSpec } from "~/components/opd_views/_shared/export_helpers";
import {
    resolveEffectivePerson,
    displayName,
    buildBodyLookup,
    bodyLabel,
    ageOf,
} from "~/lib/domain/person";
import type { PersonClient, IdentityClient, BodyClient } from "@/types/opd_db";

/* -------------------------------------------------------------------------- */
/* Person facts                                                               */
/* -------------------------------------------------------------------------- */

/** The person base block every /people/:id* loader returns. */
type PersonBaseData = {
    persons?: PersonClient | null;
    person_identities?: { items: IdentityClient[] };
    bodies?: { items: BodyClient[] };
};

/** Rich facts for the overview (a superset of the generic EntityFacts). */
interface PersonFacts {
    name: string;
    party: string | null;
    parliament: string | null;
    /** Localized birth/age clause: "Jg. 1969 (56 J.)" or "1961–2020". */
    born: string | null;
    district: string | null;
    occupation: string | null;
    /** Best single public contact value (email › website › phone). */
    contact: string | null;
    image: string | undefined;
}

/** Localized birth/age clause (`person.born{,NoAge,Died}` in loc_metas). Grammar
 *  variants are picked here in TS; only the prose lives in the JSON. */
function personBornClause(
    loc: MetaLoc,
    birthYear: string,
    deathYear: string | null,
    age: number | null,
): string {
    if (deathYear) return substitute(mt(loc, "person.bornDied"), { by: birthYear, dy: deathYear });
    return age != null
        ? substitute(mt(loc, "person.born"), { y: birthYear, age })
        : substitute(mt(loc, "person.bornNoAge"), { y: birthYear });
}

/** Overview description — leads with the facts most people search for. The
 *  assembly (which parts, in what order, with what punctuation) stays here; the
 *  prose fragments (`contactLabel`, `tail`) come from loc_metas. */
function personOverviewDesc(loc: MetaLoc, f: PersonFacts): string {
    const lead = joinParts([f.born, f.district, f.occupation], " · ");
    const contact = f.contact ? ` ${mt(loc, "person.overview.contactLabel")}${f.contact}.` : "";
    const tail = substitute(mt(loc, "person.overview.tail"), { site: SITE_NAME });
    return `${joinParts([f.name, f.party, f.parliament])}.${lead ? ` ${lead}.` : ""}${contact} ${tail}`;
}

/** Four-digit year from a (possibly partial) ISO birthday string. */
function yearOf(raw: string | null | undefined): string | null {
    const m = typeof raw === "string" ? raw.match(/^(\d{4})/) : null;
    return m ? m[1] : null;
}

/** Four-digit year from an epoch-millis deathday. */
function deathYearOf(ms: number | null | undefined): string | null {
    if (ms == null) return null;
    const d = new Date(ms);
    return Number.isNaN(d.getTime()) ? null : String(d.getUTCFullYear());
}

/**
 * Resolve the person facts most people search for, prioritized: identity, then
 * age/birth year, home district, occupation, and one public contact value.
 */
function resolvePersonFacts(
    data: PersonBaseData | null | undefined,
    lang: MetaLang,
    loc?: MetaLoc,
): PersonFacts | null {
    const persons = data?.persons;
    if (!persons) return null;
    const { person } = resolveEffectivePerson(persons, data?.person_identities?.items ?? []);
    const name = displayName(person);
    if (!name) return null;

    // `born` needs the loc bag; only the overview builder passes it. The generic
    // facts resolver (label/ctx/image for the factory) omits loc and skips born.
    const birthYear = yearOf(person.birthday);
    const deathYear = deathYearOf(person.deathday);
    let born: string | null = null;
    if (birthYear && loc) {
        born = personBornClause(loc, birthYear, deathYear, ageOf(person.birthday, person.deathday));
    }

    return {
        name,
        party: person.party_harmonized ?? person.party ?? null,
        parliament: bodyLabel(person.body_key, buildBodyLookup(data?.bodies?.items ?? [])),
        born,
        district: person.electoral_district ?? null,
        occupation: person.occupation ?? null,
        // Public contact, most-searched first. All are public parliamentary data.
        contact:
            person.email ??
            person.website_personal ??
            person.website_parliament_url ??
            person.phone ??
            null,
        image: person.image_url_oparl ?? person.image_url_external ?? undefined,
    };
}

/** Adapt the rich person facts to the generic EntityFacts the factory needs. */
const personEntityFacts = (data: PersonBaseData | null | undefined, lang: MetaLang): EntityFacts | null => {
    const f = resolvePersonFacts(data, lang);
    return f && { label: f.name, ctx: joinParts([f.party, f.parliament]), image: f.image };
};

/* -------------------------------------------------------------------------- */
/* Bulk-export Dataset JSON-LD                                                 */
/* -------------------------------------------------------------------------- */

/** The person export feeds — single source for <DataExport> and Dataset JSON-LD.
 *  Memberships surface under the `membership_groups` result key. */
export const PERSON_FEEDS: ExportFeedSpec[] = [
    { key: "votes", labelKey: "export_ds_votes" },
    { key: "access_badges", labelKey: "export_ds_access_badges" },
    { key: "contributors", labelKey: "export_ds_contributors" },
    { key: "interests", labelKey: "export_ds_interests" },
    { key: "membership_groups", labelKey: "export_ds_membership_groups" },
    { key: "speeches", labelKey: "export_ds_speeches" },
];

/** Dataset JSON-LD for the person's bulk exports (head, one per feed with rows).
 *  `about` → the same `…/people/:id#identity` node personNode emits (persons.id
 *  survives resolveEffectivePerson), so the refs resolve inside the page graph. */
const personDatasets = makeDatasets<PersonBaseData>({
    feeds: PERSON_FEEDS,
    segment: URL_PATH_SEGMENTS.PEOPLE,
    idOf: (d) => d?.persons?.id,
    scopeOf: (d, l) => personEntityFacts(d, l)?.label,
    aboutId: personNodeId,
});

/* -------------------------------------------------------------------------- */
/* Overview (/people/:id) — bespoke                                           */
/* -------------------------------------------------------------------------- */

/**
 * `/people/:id` overview. Title: "Name — Party, Chamber". Description leads with
 * the facts people google (age, canton, occupation, contact).
 */
export function personMeta(
    data: PersonBaseData | null | undefined,
    { lang, path, matches, params }: EntityMetaCtx = {},
): MetaDescriptor[] {
    const L = metaLang(lang);
    const loc = metaLoc(matches);
    const facts = resolvePersonFacts(data, L, loc);
    // One deduped @graph per page: breadcrumbs + the ProfilePage/Person nodes +
    // the bulk-export Dataset nodes.
    const graph = jsonLdTag([
        ...breadcrumbListJsonLd(matches, params),
        ...personNode(data, L, path),
        ...personDatasets(data, L, path, matches, params),
    ]);
    if (!facts) {
        return [
            ...buildMeta({
                title: SITE_NAME,
                description: personOverviewDesc(loc, {
                    name: SITE_NAME, party: null, parliament: null, born: null,
                    district: null, occupation: null, contact: null, image: undefined,
                }),
                path,
                lang: L,
            }),
            ...graph,
        ];
    }

    return [
        ...buildMeta({
            title: joinParts([facts.name, joinParts([facts.party, facts.parliament])], " — "),
            description: personOverviewDesc(loc, facts),
            path,
            lang: L,
            type: "profile",
            image: facts.image,
        }),
        ...graph,
    ];
}

/* -------------------------------------------------------------------------- */
/* Sub-route dimensions — generated by the factory                            */
/* -------------------------------------------------------------------------- */

export type PersonDimension =
    | "votes"
    | "alignment"
    | "lobby"
    | "contributions"
    | "interests"
    | "memberships"
    | "speeches"
    | "images"
    | "vocabulary";

/** The response field whose `total_count` each dimension folds in (null = none). */
const PERSON_COUNT_KEY: Record<PersonDimension, string | null> = {
    votes: "votes",
    alignment: "neighbours",
    lobby: "access_badges",
    contributions: "contributors",
    interests: "interests",
    memberships: "membership_groups",
    speeches: "speeches",
    images: "person_images",
    vocabulary: null,
};

/**
 * Meta for any `/people/:id/<dimension>` sub-route. Pulls person facts from the
 * shared base block and folds the dimension's `total_count` into a rich,
 * localized title + description. Copy: `person.dim.<dimension>.{title,desc}` in
 * loc_metas (tokens `{name}`/`{ctx}`/`{count}`).
 */
export const personDimensionMeta = makeDimensionMeta<PersonDimension, PersonBaseData>({
    resolveFacts: personEntityFacts,
    copyPrefix: "person.dim",
    countKey: PERSON_COUNT_KEY,
    type: "profile",
    node: personNode,
    datasets: personDatasets,
});

/* -------------------------------------------------------------------------- */
/* Catalog (/people) — generated by the factory                              */
/* -------------------------------------------------------------------------- */

/** `/people` catalog + search. On the clean first page, an ItemList of Person
 *  nodes (reusing `personNode`) rides along in the `@graph`. Copy:
 *  `person.index.{title,desc,searchTitle,searchDesc}` in loc_metas. */
export const peopleIndexMeta = makeIndexMeta<{
    people?: { total_count?: number; items?: PersonClient[] };
}>({
    copyPrefix: "person.index",
    countKey: "people",
    catalogueDataset: { segment: URL_PATH_SEGMENTS.PEOPLE, datasetKey: "people" },
    node: (data, lang, path) =>
        itemListJsonLd(data?.people?.items, (p) => personNode({ persons: p }, lang, path)),
});

// Re-export ctx types so route files can annotate if they wish.
export type { IndexMetaCtx };
